version: '3.8'

services:

  app-web:
    build: ./app-web
    ports:
      - "80:80"
    depends_on:
      - supmapapi

  supmapapi:
    build:
      context: ./supmap-api
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: trafine_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
