
services:

  app-web:
    build: ./app-web
    ports:
      - "80:80"
    depends_on:
      - supmapapi
    env_file:
      - ./.env

  supmapapi:
    build:
      context: ./supmap-api
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "3000:3000"

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
  

volumes:
  redis-data:
